
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: rkbart
  password: password123 
  host: localhost

development:
  <<: *default
  database: new_rails_app_development

 
production:
  primary: &primary_production
    <<: *default
    database: new_rails_app_production
    username: new_rails_app
    password: <%= ENV["NEW_RAILS_APP_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: new_rails_app_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: new_rails_app_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: new_rails_app_production_cable
    migrations_paths: db/cable_migrate
